const dummyResumes = [
  {
    id: 1,
    firstName: "John",
    middleName: "Michael",
    lastName: "Doe",
    gender: "Male",
    birthdate: "01/15/1990",
    age: "34",
    status: "Single",
    address: "123 Main Street",
    city: "New York",
    province: "NY",
    email: "john.doe@example.com",
    phone: "0917-123-4567",
    highestEducation: "Bachelor's Degree",
    schoolName: "University of Example",
    yearGraduated: "2012",
    certificates: [{ certificate: "PMP", year: "2015" }],
    employments: [
      {
        companyName: "Example Corp",
        position: "Developer",
        yearStarted: "2013",
        yearEnd: "2016",
      },
    ],
  },
  {
    id: 2,
    firstName: "Jane",
    middleName: "Marie",
    lastName: "Smith",
    gender: "Female",
    birthdate: "02/20/1988",
    age: "36",
    status: "Married",
    address: "456 Oak Avenue",
    city: "Chicago",
    province: "IL",
    email: "jane.smith@example.com",
    phone: "0917-234-5678",
    highestEducation: "Master's Degree",
    schoolName: "State University",
    yearGraduated: "2010",
    certificates: [{ certificate: "CPA", year: "2012" }],
    employments: [
      {
        companyName: "FinancePro",
        position: "Accountant",
        yearStarted: "2011",
        yearEnd: "2018",
      },
    ],
  },
  {
    id: 3,
    firstName: "Michael",
    middleName: "James",
    lastName: "Brown",
    gender: "Male",
    birthdate: "03/25/1985",
    age: "39",
    status: "Married",
    address: "789 Pine Road",
    city: "Los Angeles",
    province: "CA",
    email: "michael.brown@example.com",
    phone: "0917-345-6789",
    highestEducation: "Bachelor's Degree",
    schoolName: "California Tech",
    yearGraduated: "2007",
    certificates: [{ certificate: "AWS Certified Developer", year: "2019" }],
    employments: [
      {
        companyName: "Techy",
        position: "Cloud Engineer",
        yearStarted: "2010",
        yearEnd: "2020",
      },
    ],
  },
  {
    id: 4,
    firstName: "Emily",
    middleName: "Anne",
    lastName: "Johnson",
    gender: "Female",
    birthdate: "07/12/1992",
    age: "31",
    status: "Single",
    address: "321 Cedar Blvd",
    city: "Seattle",
    province: "WA",
    email: "emily.johnson@example.com",
    phone: "0917-456-7890",
    highestEducation: "Bachelor's Degree",
    schoolName: "Seattle University",
    yearGraduated: "2014",
    certificates: [
      { certificate: "Graphic Design Certification", year: "2015" },
    ],
    employments: [
      {
        companyName: "Creative Studio",
        position: "Designer",
        yearStarted: "2015",
        yearEnd: "Present",
      },
    ],
  },
  {
    id: 5,
    firstName: "Chris",
    middleName: "Lee",
    lastName: "Davis",
    gender: "Male",
    birthdate: "08/30/1995",
    age: "28",
    status: "Single",
    address: "654 Birch Lane",
    city: "Austin",
    province: "TX",
    email: "chris.davis@example.com",
    phone: "0917-567-8901",
    highestEducation: "Associate's Degree",
    schoolName: "Austin Community College",
    yearGraduated: "2015",
    certificates: [{ certificate: "IT Support Specialist", year: "2016" }],
    employments: [
      {
        companyName: "HelpDesk Co.",
        position: "IT Support",
        yearStarted: "2016",
        yearEnd: "2019",
      },
    ],
  },
  {
    id: 6,
    firstName: "Laura",
    middleName: "Jean",
    lastName: "Wilson",
    gender: "Female",
    birthdate: "09/10/1987",
    age: "36",
    status: "Married",
    address: "987 Spruce Street",
    city: "Denver",
    province: "CO",
    email: "laura.wilson@example.com",
    phone: "0917-678-9012",
    highestEducation: "Master's Degree",
    schoolName: "Denver University",
    yearGraduated: "2011",
    certificates: [
      { certificate: "Human Resources Certification", year: "2012" },
    ],
    employments: [
      {
        companyName: "HR Solutions",
        position: "HR Manager",
        yearStarted: "2012",
        yearEnd: "Present",
      },
    ],
  },
  {
    id: 7,
    firstName: "Daniel",
    middleName: "Victor",
    lastName: "Martinez",
    gender: "Male",
    birthdate: "11/05/1989",
    age: "34",
    status: "Single",
    address: "432 Elm Circle",
    city: "Miami",
    province: "FL",
    email: "daniel.martinez@example.com",
    phone: "0917-789-0123",
    highestEducation: "Bachelor's Degree",
    schoolName: "Miami University",
    yearGraduated: "2011",
    certificates: [{ certificate: "Data Analyst Certification", year: "2018" }],
    employments: [
      {
        companyName: "DataCorp",
        position: "Data Analyst",
        yearStarted: "2018",
        yearEnd: "2022",
      },
    ],
  },
  {
    id: 8,
    firstName: "Sophia",
    middleName: "Grace",
    lastName: "Garcia",
    gender: "Female",
    birthdate: "04/18/1994",
    age: "30",
    status: "Single",
    address: "246 Willow Way",
    city: "Phoenix",
    province: "AZ",
    email: "sophia.garcia@example.com",
    phone: "0917-890-1234",
    highestEducation: "Bachelor's Degree",
    schoolName: "Arizona State University",
    yearGraduated: "2016",
    certificates: [
      { certificate: "Digital Marketing Specialist", year: "2017" },
    ],
    employments: [
      {
        companyName: "AdWorks",
        position: "Marketing Specialist",
        yearStarted: "2017",
        yearEnd: "Present",
      },
    ],
  },
  {
    id: 9,
    firstName: "David",
    middleName: "Paul",
    lastName: "Rodriguez",
    gender: "Male",
    birthdate: "12/01/1991",
    age: "32",
    status: "Single",
    address: "111 Redwood Drive",
    city: "Portland",
    province: "OR",
    email: "david.rodriguez@example.com",
    phone: "0917-901-2345",
    highestEducation: "Bachelor's Degree",
    schoolName: "Portland State",
    yearGraduated: "2014",
    certificates: [{ certificate: "Business Administration", year: "2015" }],
    employments: [
      {
        companyName: "BizPro",
        position: "Business Analyst",
        yearStarted: "2015",
        yearEnd: "2020",
      },
    ],
  },
  {
    id: 10,
    firstName: "Olivia",
    middleName: "Rose",
    lastName: "Hernandez",
    gender: "Female",
    birthdate: "05/07/1993",
    age: "31",
    status: "Married",
    address: "555 Chestnut Lane",
    city: "Atlanta",
    province: "GA",
    email: "olivia.hernandez@example.com",
    phone: "0917-012-3456",
    highestEducation: "Bachelor's Degree",
    schoolName: "Georgia Tech",
    yearGraduated: "2015",
    certificates: [
      { certificate: "Cybersecurity Certification", year: "2019" },
    ],
    employments: [
      {
        companyName: "SecureNet",
        position: "Cybersecurity Specialist",
        yearStarted: "2019",
        yearEnd: "Present",
      },
    ],
  },
  {
    id: 11,
    firstName: "Ethan",
    middleName: "Andrew",
    lastName: "Lopez",
    gender: "Male",
    birthdate: "06/22/1990",
    age: "33",
    status: "Single",
    address: "888 Sycamore Road",
    city: "Dallas",
    province: "TX",
    email: "ethan.lopez@example.com",
    phone: "0917-123-4567",
    highestEducation: "Bachelor's Degree",
    schoolName: "University of Texas",
    yearGraduated: "2012",
    certificates: [
      { certificate: "Full Stack Developer Certification", year: "2016" },
    ],
    employments: [
      {
        companyName: "DevHouse",
        position: "Software Engineer",
        yearStarted: "2017",
        yearEnd: "Present",
      },
    ],
  },
  {
    id: 12,
    firstName: "Ava",
    middleName: "Claire",
    lastName: "Gonzalez",
    gender: "Female",
    birthdate: "09/14/1996",
    age: "27",
    status: "Single",
    address: "777 Oakwood Street",
    city: "Las Vegas",
    province: "NV",
    email: "ava.gonzalez@example.com",
    phone: "0917-234-5678",
    highestEducation: "Bachelor's Degree",
    schoolName: "University of Nevada",
    yearGraduated: "2018",
    certificates: [
      { certificate: "Event Management Certificate", year: "2019" },
    ],
    employments: [
      {
        companyName: "Eventify",
        position: "Event Coordinator",
        yearStarted: "2019",
        yearEnd: "Present",
      },
    ],
  },
  {
    firstName: "James",
    middleName: "Robert",
    lastName: "Perez",
    gender: "Male",
    birthdate: "03/11/1989",
    age: "35",
    status: "Married",
    address: "999 Cedar Park",
    city: "San Diego",
    province: "CA",
    email: "james.perez@example.com",
    phone: "0917-345-6789",
    highestEducation: "Master's Degree",
    schoolName: "San Diego State",
    yearGraduated: "2013",
    certificates: [{ certificate: "MBA", year: "2013" }],
    employments: [
      {
        companyName: "BusinessWorld",
        position: "Operations Manager",
        yearStarted: "2014",
        yearEnd: "Present",
      },
    ],
  },
  {
    id: 13,
    firstName: "Isabella",
    middleName: "Faith",
    lastName: "Ramirez",
    gender: "Female",
    birthdate: "01/27/1997",
    age: "27",
    status: "Single",
    address: "1122 Maple Street",
    city: "Orlando",
    province: "FL",
    email: "isabella.ramirez@example.com",
    phone: "0917-456-7890",
    highestEducation: "Bachelor's Degree",
    schoolName: "University of Central Florida",
    yearGraduated: "2019",
    certificates: [{ certificate: "UX Design Certificate", year: "2020" }],
    employments: [
      {
        companyName: "DesignWorks",
        position: "UX Designer",
        yearStarted: "2020",
        yearEnd: "Present",
      },
    ],
  },
  {
    id: 14,
    firstName: "Benjamin",
    middleName: "Thomas",
    lastName: "Sanchez",
    gender: "Male",
    birthdate: "07/30/1992",
    age: "31",
    status: "Single",
    address: "3344 River Road",
    city: "Houston",
    province: "TX",
    email: "benjamin.sanchez@example.com",
    phone: "0917-567-8901",
    highestEducation: "Bachelor's Degree",
    schoolName: "University of Houston",
    yearGraduated: "2014",
    certificates: [
      { certificate: "Network Engineer Certificate", year: "2015" },
    ],
    employments: [
      {
        companyName: "NetSystems",
        position: "Network Engineer",
        yearStarted: "2015",
        yearEnd: "2021",
      },
    ],
  },
];
